MoCha/models/Article.php
<?php

namespace app\models;

/**
 * This is the model class for table "mc_article".
 *
 * @property string $id
 * @property string $user_id
 * @property string $name
 * @property string $title
 * @property string $category_id
 * @property string $description
 * @property string $content
 * @property integer $position
 * @property string $link_id
 * @property string $cover_id
 * @property integer $display
 * @property integer $attach
 * @property string $view
 * @property string $comment
 * @property integer $level
 * @property integer $status
 * @property string $template
 * @property string $created
 * @property string $modified
 */
class Article extends \yii\db\ActiveRecord
{
    const STATUS_ACTIVE=1;
    const STATUS_NOACTIVE=0;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%article}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'category_id', 'position', 'link_id', 'cover_id', 'display', 'attach', 'view', 'comment', 'level', 'status', 'created', 'modified'], 'integer'],
            [['content'], 'required'],
            [['content'], 'string'],
            [['name'], 'string', 'max' => 40],
            [['title'], 'string', 'max' => 80],
            [['description'], 'string', 'max' => 140],
            [['template'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '文档ID',
            'user_id' => '用户',
            'name' => '标识',
            'title' => '标题',
            'category_id' => '分类',
            'description' => '描述',
            'content' => '文章内容',
            'position' => '推荐位',
            'link_id' => '外链',
            'cover_id' => '封面',
            'display' => '可见性',
            'attach' => '附件数量',
            'view' => '浏览量',
            'comment' => '评论数',
            'level' => '优先级',
            'status' => '数据状态',
            'template' => '详情页显示模板',
            'created' => '创建时间',
            'modified' => '更新时间',
        ];
    }

    /**
     * @return Profile $user
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return Profile $category
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
}

MoCha/controllers/ArticleController.php
<?php

namespace app\controllers;

use Yii;
use app\componets\Ya;
use app\models\Article;
use app\models\ArticleSearch;
use app\models\Category;
use app\controllers\BaseController;
use yii\web\NotFoundHttpException;
use yii\web\VerbFilter;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends BaseController
{
    public $layout = '/main';

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex($category = '')
    {
        $where['module'] = Category::MODULE_ARTICLE;
        if (!empty($category)) {
            $where['name'] = $category;
        }
        $categorys = Category::find()->where($where)->column();
        $models = Article::find()->where(['status' => Article::STATUS_ACTIVE, 'category_id' => $categorys])->with('category')->all();
        //dump($models);

        return $this->render('index', [
            'models' => $models,
        ]);
    }

    /**
     * Lists sub category with Article models.
     * @return mixed
     */
    public function actionList($category, $page = 1)
    {
        $cat = Category::findByName($category);
        if ($cat) {
            $view = $cat->template_lists ?: 'list';

            if ($cat->childs == 0) {
                $categorys = $cat->id;
            } else {
                $categorys = Category::find()
                    ->where(['like', 'parents', $cat->id . '|'])
                    ->andWhere(['childs' => 0])
                    ->column();
            }
            
            $models = Article::find()
                ->where(['status' => Article::STATUS_ACTIVE, 'category_id' => $categorys])
                ->with('category')
                ->all();

            return $this->render($view, [
                'models' => $models,
                'category' => $cat,
            ]);
        } else {
            throw new NotFoundHttpException('亲请求的页面找不到了喔！');
        }
    }

    public function actionA()
    {
        return $this->renderPartial('a');
    }

    /**
     * Displays a single Article model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id, $category)
    {
        $model = $this->findModel($id);
        if ($model->category && ($model->category->name == $category)) {
            $view = $model->category->template_detail ?: 'view';
            return $this->render($view, [
                'model' => $model,
            ]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if ($id !== null && ($model = Article::find($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

MoCha/views/article/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\Article $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'category_id')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'position')->textInput() ?>

    <?= $form->field($model, 'link_id')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'cover_id')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'display')->textInput() ?>

    <?= $form->field($model, 'attach')->textInput() ?>

    <?= $form->field($model, 'view')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'comment')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'level')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'created')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'modified')->textInput(['maxlength' => 10]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 40]) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 80]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => 140]) ?>

    <?= $form->field($model, 'template')->textInput(['maxlength' => 100]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

MoCha/views/article/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\ArticleSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'category_id') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'content') ?>

    <?php // echo $form->field($model, 'position') ?>

    <?php // echo $form->field($model, 'link_id') ?>

    <?php // echo $form->field($model, 'cover_id') ?>

    <?php // echo $form->field($model, 'display') ?>

    <?php // echo $form->field($model, 'attach') ?>

    <?php // echo $form->field($model, 'view') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <?php // echo $form->field($model, 'level') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'template') ?>

    <?php // echo $form->field($model, 'created') ?>

    <?php // echo $form->field($model, 'modified') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

MoCha/views/article/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Article $model
 */

$this->title = 'Create Article';
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

MoCha/views/article/index.php
<?php

use app\components\Ya;
use yii\helpers\Html;
$this->title = 'Articles';
$this->params['breadcrumbs'][] = $this->title;
$this->params['body'] = 'page-category';
?>
                    <h2 class="heading_title"><span>网站公告</span></h2>
                    <div class="category-list clearfix">
                        <ul class="col-md-12">
                            <?php foreach ($models as $model): ?>
                            <li>
                                <div class="col-lg-1"><a href="<?= Ya::toRoute(['/article/list/', 'category'=>$model->category->name]) ?>"><span class="label label-primary"><?= $model->category->name ?></span></a></div>
                                <div class="col-lg-10"><?= Ya::a($model->title, ['/article/view', 'id' => $model->id, 'category' => $model->category->name]) ?></div>
                                <div class="col-lg-1"><span class="badge pull-right"><?= Ya::asDate($model->modified) ?></span></div>
                            </li>
                            <?php endforeach;?>
                        </ul>
                    </div>

MoCha/views/article/list.php
<?php

use app\components\Ya;
use yii\helpers\Html;
use yii\widgets\Menu;
use app\widgets\NewsCategory;

$this->title = $category->title;
$this->params['breadcrumbs'][] = $this->title;
$this->params['body'] = 'page-category';
?>
            <section class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                <!--<div class="success">这是一个提示信息</div>-->
                <div id="content">
                    <div class="category-info clearfix">
                        <div class="image"><img src="/statics/images/demo/img-category-873x250.jpg" alt="Mac" /></div>
                    <h2 class="heading_title"><span><?= $category->title ?></span></h2>
                        <div class="description">
                            <?= NewsCategory::widget(['category_id' => 1]) ?>

                        </div>
                    </div>
                    <div class="category-list clearfix">
                        <ul class="col-md-12">
                            <?php foreach ($models as $model): ?>
                            <li>
                                <?php if($category->childs):?>
                                    <div class="col-lg-1"><a href="<?= Ya::toRoute(['/article/list/', 'category'=>$model->category->name]) ?>"><span class="label label-primary"><?= $model->category->title ?></span></a></div>
                                <?php endif;?>
                                <div class="col-lg-10"><?= Ya::a($model->title, ['/article/view', 'id' => $model->id, 'category' => $model->category->name]) ?></div>
                                <div class="col-lg-1"><span class="badge pull-right"><?= Ya::asDate($model->modified) ?></span></div>
                            </li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                        
                    
                </div>
            </section>
            <aside class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <div id="column-left" class="sidebar">
                    <div id="column-right" class="sidebar">
                        




                        <div class="box">
                            <div class="box-heading"><span>交易记录</span></div>
                            <div class="box-content  col-lg-12">
                                <?= Menu::widget(array(
                                    'items'=>array(
                                        array(
                                            'label'=>'配货管理',
                                            'url'=>array('/seller/invoice'),
                                            'options'=>array('css' => 'haschild'),
                                        ),
                                        array(
                                            'label'=>'刷单管理',
                                            'url'=>array('/seller/fake'),
                                            'options'=>array('css' => 'haschild'),
                                        ),
                                        array(
                                            'label'=>'售后服务',
                                            'url'=>array('/seller/service'),
                                            'options'=>array('css' => 'haschild'),
                                            'items'=>array(
                                                array('label'=>'换货记录', 'url'=>array('/seller/service/niffer'), 'active'=> true),
                                                array('label'=>'换货记录', 'url'=>array('/seller/service/niffer'), 'linkOptions'=>array('class'=>'corner-all')),
                                                array('label'=>'换货记录', 'url'=>array('/seller/service/niffer'), 'linkOptions'=>array('class'=>'corner-all')),
                                                array('label'=>'换货记录', 'url'=>array('/seller/service/niffer'), 'linkOptions'=>array('class'=>'corner-all')),
                                            )
                                        ),
                                    ),
                                    'submenuTemplate' => "\n<ul class=\"list\">\n{items}\n</ul>\n",
                                    //'labelTemplate' => '{label}',
                                    //'itemOptions'=>array('css' => 'box-category list'),
                                    'options'=>array('class'=>'box-category list'),
                                    //'encodeLabels'=>false
                                )); ?>
                            </div>
                            <div class="box-heading"><span>会员中心</span></div>
                            <div class="box-content">
                                <ul class="list">
                                    <li class="active"><?= Ya::a('退出登录', ['/account/default/logout']) ?></li>
                                    <li><?= Ya::a('验证邮箱', ['/account/confirm/']) ?></li>
                                    <li><?= Ya::a('个人资料', ['/account/profile/']) ?></li>
                                    <li><?= Ya::a('修改资料', ['/account/settings/']) ?></li>
                                    <li><?= Ya::a('修改邮箱', ['/account/settings/email']) ?></li>
                                    <li><?= Ya::a('修改密码', ['/account/settings/password']) ?></li>
                                </ul>
                            </div>

                            <div class="box-heading"><span>个人设置</span></div>
                            <div class="box-content">
                                <ul class="list">
                                    <li><?= Ya::a('个人资料', ['/account/settings/']) ?></li>
                                    <li><?= Ya::a('验证邮箱', ['/account/confirm/']) ?></li>
                                    <li><?= Ya::a('修改邮箱', ['/account/settings/email']) ?></li>
                                    <li><?= Ya::a('修改密码', ['/account/settings/password']) ?></li>
                                    <li><?= Ya::a('退出登录', ['/account/default/logout']) ?></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </aside>
            

MoCha/views/article/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Article $model
 */

$this->title = 'Update Article: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="article-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

MoCha/views/article/view.php
<?php

use app\components\Ya;

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['body'] = 'page-category';
?>
                    <h1><?=$model->title?></h1>
                    <div class="category-info clearfix">
                        <div class="image">
                            <img src="/Statics/images/demo/img-blog5-900x350w.jpg" alt="Mac" />
                        </div>
                        <div class="description">
                            <p><?=$model->description?></p>
                            <ul class="list-inline">
                                <li><span class="fa fa-clock-o"><?=$model->getAttributeLabel('modified')?>:</span> <?=Yii::$app->formatter->asDate($model->modified)?></li>
                                <li><span class="fa fa-pencil"><?=$model->getAttributeLabel('user_id')?>:</span> <?=Ya::encode($model->user->username)?></li>
                                <li><span class="fa fa-eye"><?=$model->getAttributeLabel('view')?>:</span> <?=Ya::encode($model->view)?></li>
                                <li><span class="fa fa-comments"><?=$model->getAttributeLabel('comment')?>:</span> <?=Ya::encode($model->comment)?></li>
                                <li><span class="fa fa-comments"><?=$model->getAttributeLabel('category_id')?>:</span> <?=Ya::encode($model->category->title)?></li>
                            </ul>
                            
                        </div>
                    </div>
                    <div class="category-list clearfix">
                        <?=$model->content?>
                    </div>